# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def build(bld):
    module = bld.create_ns3_module('red', ['internet', 'network', 'point-to-point'])
    module.source = [
        'model/dev-red-queue.cc',
        'model/dev-red-queue-ppp.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'red'
    headers.source = [
        'model/dev-red-queue.h',
        'model/dev-red-queue-ppp.h',
        ]
