# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('cosim-example', ['cosim'])
    obj.source = 'cosim-example.cc'

    obj = bld.create_ns3_program('cosim-bridge-example', ['cosim', 'bridge'])
    obj.source = 'cosim-bridge.cc'

    obj = bld.create_ns3_program('cosim-dumbbell-example', ['cosim', 'bridge'])
    obj.source = 'cosim-dumbbell.cc'

